image: python:3.9.12

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install requirements.txt

test:
  script:
    - python HotelDjango/manage.py test paradise
