stages:
  - test
  - build
  - deploy

test:
  image: python:3.9.12-alpine
  stage: test
  tags:
    - paradise
  script:
    - pip install -r requirements.txt
    - python HotelDjango/manage.py makemigrations
    - python HotelDjsngo/manage.py test

cptoserver:
  stage: build
  tags:
    - paradise
  script:
    - cd ..
    - cp -R ./hotelparadise /home/paradisetest
    - docker-compose -f docker-compose.dev.yml up -d --build


#image: python:3.9.12
#я откдючил общие бегуны
#before_script:
#  - python --version
#  - pip install virtualenv
#  - virtualenv venv
#  - source venv/bin/activate
#  - pip install requirements.txt
#
#test:
#  script:
#    - python HotelDjango/manage.py test paradise
#  tags:
#    - paradise

