stages:
#  - test
  - build
  - deploy

#test:
#  image: python:3.9.12-alpine
#  stage: test
#  before_script:
#    - apk add postgresql-dev gcc python3-dev musl-dev
#    - pip install --upgrade pip
#    - pip install -r requirements.txt
#  tags:
#    - paradise
#  script:
#    - pip install -r requirements.txt
#    - python HotelDjango/manage.py makemigrations
#    - python HotelDjango/manage.py test paradise

cptoserver:
  stage: build
  tags:
    - paradise
  script:
    - cd ..
    - cp -R ./hotelparadise /home/paradisetest

sshdocker:
  stage: deploy
  tags:
    - ssh
  script:
    - sudo su
    - ssh root@31.172.67.174:22 ls
#image: python:3.9.12
#я откдючил общие бегуныaaaasd
#before_script:
#  - python --version
#  - pip install virtualenv
#  - virtualenv venv
#  - source venv/bin/activate
#  - pip install requirements.txt
#
#test:
#  script:
#    - python HotelDjango/manage.py test paradise
#  tags:
#    - paradise

