stages:
  - build
#  - test
#  - deploy
mkdir:
  stage: build
  tags:
    - paradise
  script:
    - ls
    - pwd


#image: python:3.9.12
#я откдючил общие бегуны
#before_script:
#  - python --version
#  - pip install virtualenv
#  - virtualenv venv
#  - source venv/bin/activate
#  - pip install requirements.txt
#
#test:
#  script:
#    - python HotelDjango/manage.py test paradise
#  tags:
#    - paradise

