stages:
#  - test
  - build
  - deploy

#test:
#  image: python:3.9.12-alpine
#  stage: test
#  before_script:
#    - apk add postgresql-dev gcc python3-dev musl-dev
#    - pip install --upgrade pip
#    - pip install -r requirements.txt
#  tags:
#    - paradise
#  script:
#    - pip install -r requirements.txt
#    - python HotelDjango/manage.py makemigrations
#    - python HotelDjango/manage.py test paradise

cptoserver:
  stage: build
  tags:
    - paradise
  script:
    - cd ..
    - cp -R ./hotelparadise /home/paradisetest

sshdocker:
  stage: deploy
  tags:
    - ssh
#  before_script:
#    - apk add --update --no-cache openssh sshpass
  script:
    - ssh -tt root@31.172.67.174
#    - ssh -Tt root@31.172.67.174 | sshpass -p zGC1zCTtay07rhYF
# - sshpass -p 'zGC1zCTtay07rhYF'
#    - ssh root@31.172.67.174:22 lsa
#image: python:3.9.12ф
#я откдючил общие бегуныaaaasd
#before_script:
#  - python --version
#  - pip install virtualenv
#  - virtualenv venv
#  - source venv/bin/activatef
#  - pip install requirements.фtxt
#
#test:
#  script:
#    - python HotelDjango/manage.py test paradise
#  tags:
#    - paradise

