version: '3.7'
services:
  dj_web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python /usr/src/app/HotelDjango/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - hotel_db
  hotel_db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=hotel_loo
volumes:
  postgres_data: