version: '3.7'
services:
  dj_web:

#    image: chechkysh/hotelparadise_dj_web:2.1.4
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "python manage.py collectstatic --noinput && nginx && gunicorn --certfile=/etc/nginx/fullchain.pem --keyfile=/etc/nginx/privkey.pem --bind 0.0.0.0:8000 HotelDjango.wsgi:application server --log-level debug"
    ports:
      - 8081:8081
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - hotel_db
    volumes:
      - certs:/etc/nginx/
  hotel_db:
    restart: on-failure
    image: postgres:14.4-alpine
    volumes:
      - hotel_postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=looparadiseadmin
      - POSTGRES_PASSWORD=looparadiseadmin
      - POSTGRES_DB=looparadise
  front:
    container_name: "hotelfront"
    build:
      context: ./Front
      dockerfile: Dockerfile_front
    volumes:
      - front:/usr/src/app/build
volumes:
  hotel_postgres_data:
  certs:
  front: