# Generated by Django 4.0.4 on 2022-04-27 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStatuses',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=16, verbose_name='Статус брони')),
            ],
        ),
        migrations.CreateModel(
            name='DateStatuses',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=16, verbose_name='Состояние промежутка дат')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('link_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Ссылки на фото',
                'verbose_name_plural': 'Ссылки на фото',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('phone_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Номер телефона')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('father_name', models.CharField(max_length=32, verbose_name='Отчество')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заметки, описание')),
            ],
            options={
                'verbose_name': 'Гости',
                'verbose_name_plural': 'Гости',
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Дата начала ценового промежутка')),
                ('finish_date', models.DateField(verbose_name='Дата конца ценового промежутка')),
                ('price', models.IntegerField(verbose_name='Цена в заданный промежуток')),
            ],
            options={
                'verbose_name': 'Цены',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Номер комнаты')),
                ('description', models.CharField(blank=True, max_length=512, verbose_name='Описание комнаты')),
                ('links', models.ManyToManyField(blank=True, to='paradise.links', verbose_name='Ссылки на фотографии комнаты')),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paradise.prices', verbose_name='Цена в период')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='DateArray',
            fields=[
                ('array_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('arrive_date', models.DateField(verbose_name='Начало промежутка дат')),
                ('leave_date', models.DateField(verbose_name='Конец промежутка дат')),
                ('date_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paradise.datestatuses', verbose_name='Статус промежутка дат')),
            ],
            options={
                'verbose_name': 'Состояние дат',
                'verbose_name_plural': 'Состояние дат',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Номер брони')),
                ('book_creation_date', models.DateField(auto_now_add=True, verbose_name='Дата создания брони')),
                ('book_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paradise.bookstatuses', verbose_name='Статус брони')),
                ('dates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paradise.datearray', verbose_name='Даты брони')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paradise.person', verbose_name='Гость')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paradise.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Брони',
                'verbose_name_plural': 'Брони',
            },
        ),
    ]
