# Generated by Django 4.1.1 on 2022-10-14 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateStatuses',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=16, verbose_name='Состояние промежутка дат')),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Дата начала ценового промежутка')),
                ('finish_date', models.DateField(verbose_name='Дата конца ценового промежутка')),
                ('price', models.IntegerField(verbose_name='Цена в заданный промежуток')),
            ],
            options={
                'verbose_name': 'Цены',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Номер комнаты')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=512, verbose_name='Описание комнаты')),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paradise.prices', verbose_name='Цена в период')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('link_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='paradise.room')),
            ],
            options={
                'verbose_name': 'Ссылки на фото',
                'verbose_name_plural': 'Ссылки на фото',
            },
        ),
        migrations.CreateModel(
            name='DateArray',
            fields=[
                ('array_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('arrive_date', models.DateField(verbose_name='Начало промежутка дат')),
                ('leave_date', models.DateField(verbose_name='Конец промежутка дат')),
                ('date_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paradise.datestatuses', verbose_name='Статус дат')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='paradise.room')),
            ],
            options={
                'verbose_name': 'Состояние дат',
                'verbose_name_plural': 'Состояние дат',
            },
        ),
    ]
