#FROM node:14-alpine
#
#WORKDIR /usr/src/app
#
#COPY . .
#
#RUN npm install
#
#RUN npm run build

# pull official base image
FROM node:16-alpine

# set working directory
WORKDIR /usr/src/app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY . .
RUN npm cache clean --force
RUN npm install
RUN npm run build

# add app
